### ISSUE TITLE
FEAT - toogle status

### ISSUE THREAD

**Issue by Fernnandez** [Fernnandez/riquinho-app#22]
Eu como usuário desejo ter a possibilidade de mudar o status das transações diretamente da listagem com um botão ou checkbox para facilitar o uso da aplicação

---
### Critérios de aceite
- Deve ser possível mudar o status da transação diretamente de algum gatilho na listagem

---
### Subtasks
- [x] Criar rota PATH para mudar o status da transação na api
- [x] Ajustar Item da transação para ter o novo botão de ação para o toggle de status

**Comment by miguelgabriel01** [comment]
CURL do endpoint:

curl --location --request PATCH 'http://localhost:3002/transacao/df5baa11-4903-4e63-aad4-f1978ba4e67b' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNDY5YjQ2OC04MzYyLTQ1YzYtYjBkNi0xMzYxYmVhMjc5NWUiLCJlbWFpbCI6Im1nYnNAZ21haWwuY29tIiwiaWF0IjoxNjYyNTE0MjAxLCJleHAiOjE2NjI2MDA2MDF9.XC0rIsCSsTAlTbUAQbO6P289UoZMFbmdQZs_ai9qmuQ'
