### ISSUE TITLE
Estudos nestJS

### ISSUE THREAD

**Issue by miguelgabriel01** [Fernnandez/riquinho-app#23]
Eu como desenvolvedor, estou estudando NestJS para melhorar meu desenvolvimento na tecnologia

**Comment by miguelgabriel01** [comment]
conteúdos estudados:

https://www.treinaweb.com.br/blog/criando-o-primeiro-crud-com-nestjs

https://medium.com/@iago.maiasilva/construindo-uma-api-com-nestjs-postgresql-e-docker-parte-1-criando-nosso-primeiro-endpoint-248d4b8ecc9c

https://www.sidechannel.blog/criando-uma-api-com-nestjs/

https://www.youtube.com/watch?v=cBIUOL6MFXw&t=472s

**Comment by lilialnas** [comment]
@miguelgabriel01 Faltou pontuar essa spike

**Comment by miguelgabriel01** [comment]
https://docs.google.com/document/d/1Ax3Xl-FPR2sHnXSNI48HuUGeXQreTigZWm3gRZxH3Xk/edit?usp=sharing
