### ISSUE TITLE
Estudo de viabilidade de importação de PDF 

### ISSUE THREAD

**Issue by lilialnas** [Fernnandez/riquinho-app#26]
Selecionar uma fatura de um determinado cartão de crédito e verificar como podemos coletar os dados de um PDF.
Os principais dados a serem coletados são para fazer a importação para despesas ( Data, descrição, valor).
Não é necessário importar uma categoria, usaremos uma default para importação

Verificar quais tecnologias disponíveis ou até projetos que já façam isso.

**Comment by Pedrohsmarinho** [comment]
Segue em anexo o review da squad da criação ou não da feature de importação de pfd

[Review da importação de pdf](https://childlike-echidna-e10.notion.site/Viabilidade-de-importa-o-de-PDF-95712de8e01d41008beeeb32159c05db)
